-- Snowflake configuration for the "Find a Movie" project

CREATE DATABASE DB_FIND_A_MOVIE;
USE DATABASE DB_FIND_A_MOVIE;
CREATE WAREHOUSE DW_FIND_A_MOVIE;
USE WAREHOUSE DW_FIND_A_MOVIE;

CREATE SCHEMA BRONZE;
CREATE SCHEMA SILVER;
CREATE SCHEMA GOLD;

CREATE USER DATA_PIPELINE_USER;
ALTER USER DATA_PIPELINE_USER SET TYPE = SERVICE;
ALTER USER DATA_PIPELINE_USER SET RSA_PUBLIC_KEY = 'MIIBI(...)AB';
CREATE ROLE DATA_PIPELINE_ROLE;
GRANT ROLE DATA_PIPELINE_ROLE TO USER DATA_PIPELINE_USER;

DESC USER DATA_PIPELINE_USER;

GRANT USAGE ON DATABASE DB_FIND_A_MOVIE TO ROLE DATA_PIPELINE_ROLE;
GRANT USAGE ON WAREHOUSE DW_FIND_A_MOVIE TO ROLE DATA_PIPELINE_ROLE;
GRANT USAGE ON SCHEMA BRONZE TO ROLE DATA_PIPELINE_ROLE;
GRANT USAGE ON SCHEMA SILVER TO ROLE DATA_PIPELINE_ROLE;
GRANT USAGE ON SCHEMA GOLD TO ROLE DATA_PIPELINE_ROLE;

GRANT CREATE TABLE ON SCHEMA BRONZE TO ROLE DATA_PIPELINE_ROLE;
GRANT CREATE VIEW ON SCHEMA BRONZE TO ROLE DATA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA BRONZE TO ROLE DATA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL VIEWS IN SCHEMA BRONZE TO ROLE DATA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA BRONZE TO ROLE DATA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE VIEWS IN SCHEMA BRONZE TO ROLE DATA_PIPELINE_ROLE;

GRANT CREATE TABLE ON SCHEMA SILVER TO ROLE DATA_PIPELINE_ROLE;
GRANT CREATE VIEW ON SCHEMA SILVER TO ROLE DATA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA SILVER TO ROLE DATA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL VIEWS IN SCHEMA SILVER TO ROLE DATA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA SILVER TO ROLE DATA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE VIEWS IN SCHEMA SILVER TO ROLE DATA_PIPELINE_ROLE;

GRANT CREATE TABLE ON SCHEMA GOLD TO ROLE DATA_PIPELINE_ROLE;
GRANT CREATE VIEW ON SCHEMA GOLD TO ROLE DATA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA GOLD TO ROLE DATA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL VIEWS IN SCHEMA GOLD TO ROLE DATA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA GOLD TO ROLE DATA_PIPELINE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE VIEWS IN SCHEMA GOLD TO ROLE DATA_PIPELINE_ROLE;

GRANT ROLE DATA_PIPELINE_ROLE TO ROLE ACCOUNTADMIN;
GRANT ROLE DATA_PIPELINE_ROLE TO ROLE SYSADMIN;

SELECT * FROM DB_FIND_A_MOVIE.GOLD.DIM_GENRE ORDER BY GENRE_ID;

SELECT COUNT(1) FROM DB_FIND_A_MOVIE.BRONZE.BASE_BRONZE_TMDB_MOVIE_RAW;

SELECT *
FROM DB_FIND_A_MOVIE.BRONZE.TMDB_MOVIE_RAW
;